red-hat-storage/odf-operator

controllers/quickstart_constants.go, controllers/quickstarts.go, controllers/quickstarts_test.go, controllers/storagesystem_controller.go, controllers/storagesystem_controller_fake.go, go.mod, go.sum, main.go
For 4.9 release, OCS operator will be replaced with the ODF at a higher level. Hence we would want to make sure that new quickstarts accurately represent the workflows for ODF operator.
This commit includes all the relevant changes that are applicable to newer UI that is coming as part of OCP 4.9
**What is a QuickStart ?**
Quick starts walk users through completing different tasks in the console. In OpenShift 4.7, we added a quick start custom resource. This allows operators and administrators to contribute new quick starts to the cluster beyond the out-of-the-box set. Typically, quick starts for operators are created by the operator itself after the operator is installed.
**What does this PR add ?**
This commit adds ensureQuickStarts and relevant dependencies to initialize the new …
=> Adds quickstarts to ODF operator

.github/workflows/commitlint.yaml, .github/workflows/conf/commitlintrc.json, CONTRIBUTING.md
commitlint will force a developer to write a commit as per our guidelines
reference links:
Naming Conventions -> https://commitlint.js.org/#/concepts-commit-conventions                                                                                                   
Rules -> https://commitlint.js.org/#/reference-rules
=> action: Add commitlint action for checking commits

controllers/conditions.go
Fix Panic:
non-string key argument passed to logging, ignoring all later arguments.
=> controllers: Fix loggig panic

bundle/manifests/odf-operator.clusterserviceversion.yaml, bundle/manifests/odf.openshift.io_storagesystems.yaml, config/crd/kustomization.yaml, config/default/kustomization.yaml, main.go
To run a webhook via OLM it has a technical requirement that webhooks can not have the API groups same as OLM. So technically we can not contain the subscription webhook and its requirements in the CSV. remove the same from the CSV.
Error seen:
Webhook rules cannot include the OLM group
workarounds i can think of:
We might be able to create a job for this.
we can create a webhook deployment in the controller itself.
=> stop running webhook as a manager

bundle/metadata/dependencies.yaml, hack/make-bundle-vars.mk
Add "ocs-operator" as a dependency of odf
Add "ocs-operator" and "ibm-storage-odf-operator" bundle images to build
within our catalog image.
=> Add bundle dependency

controllers/defaults.go, controllers/flashsystemcluster.go, controllers/subscriptions.go
remove the constant values and define a map of default values. Which
will be used only if env var is not set/defined.
=> controllers: use env var instead of hardcoded values

.github/workflows/dependencies.yaml
We can block the PR from merging and wait for its dependencies to be merged via adding `Depends on #<>`
=> action: Add action to wait for dependent PR to be merged

main.go
Fix: no kind is registered for the type v1alpha1.FlashSystemCluster
in scheme.
=> controllers: Fix scheme issue via adding ibm scheme

controllers/storagecluster_controller.go, controllers/storagecluster_controller_test.go
Append "-storagesystem" in the name of storagesystem while creating
storagesystem for the storagecluster.
=> controllers: Append "-storagesystem" while creating storagesystem

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/console/console_init.yaml, config/default/manager_auth_proxy_patch.yaml, config/rbac/role.yaml, console/console.go
CRUD permissions for deployment, services and consoleplugins is required for ODF Console to function properly.
=> Bug 1994261: Add required permissions for console to initialize properly

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/manifests/bases/odf-operator.clusterserviceversion.yaml
create a openshift-storage namespace via UI automatically while
installing the operator.
=> bundle: create a namespace automatically via UI if not one present

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/console/console_init.yaml, config/manifests/bases/odf-operator.clusterserviceversion.yaml
- Use official images for ODF Console from quay repository. 
- Update CSV annotations to identify ODF Operator as a dynamic plugin carrier.
=> bundle: Update CSV to use official console image and add console annotation

config/install/ibm-storage-odf-operator-subscription.yaml, config/install/odf-catalogsource.yaml, config/install/odf-operator-subscription.yaml
create odf-catalogsource in openshift-storage namespace instead of
openshift-marketplace while installing via `make deploy-with-olm`.
=> bundle: Change odf-catalogsource namespace

api/v1alpha1/storagesystem_types.go, bundle/manifests/odf.openshift.io_storagesystems.yaml, config/crd/bases/odf.openshift.io_storagesystems.yaml, controllers/conditions.go, controllers/storagesystem_controller.go, controllers/subscriptions.go, controllers/vendor_test.go, controllers/vendors.go
Mark storage system as ready if csv is ready, either underlying storage
CR is present or not, so that UI can create a IBM flashsystem based on
its phase.
Without this change UI will never be able to create a IBM flashsystem.
=> controllers: Add and update conditions in storageSystem controller

controllers/delete.go, controllers/quickstarts.go, controllers/quickstarts_test.go
This commit adds quickstart cleanup when deleting StorageSystem or
uninstalling the operator
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> Delete quickstarts when removing StorageSystem

main.go
Managing the dependent Subscriptions introduced a paradox where we are
trying to watch for a resource type that doesn't exist yet... and
controller-runtime does not like this. This patch temporarily removes
the setup of the StorageCluster controller to work around the CLBO, for
testing purposes, a more appropriate resolution is being developed.
For this PR, I have verified both installation of ODF 4.8 and upgrade from OCS 4.8 to ODF 4.9 using the following resources: https://github.com/jarrpa/ocs-operator/tree/jarrpa-dev-master/upgrade-testing
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
=> controllers: remove setup for StorageCluster controller

controllers/storagesystem_controller.go, controllers/subscriptions.go, controllers/subscriptions_test.go, main.go
This PR pre-creates the OCS Subscription so as to re-enable the StorageClusterReconciler that was giving us CLBO after #99 was merged too hastily. The bug itself was that controller-runtime was expecting the StorageCluster CRD to exist *before* the controller manager is started, hence we are now creating the Subscription in `StorageSystemReconciler.SetupWithManager()`.
I really really REALLY REALLY don't like this, but I'm going through with it as a workaround for the installation and upgrade blockers in release-4.9. We'll need to take time to carefully consider a proper fix for this.
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
=> [HACK] pre-create OCS Subscriptions in StorageSystemReconciler.SetupWithManager()

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/subscription_controller.go, controllers/subscriptions.go
Manual strategy is kind of pain for managed operators for a user in the
UI as User can not approve them very easily. Handling them via the
operators itself will be a really useful for the one click smooth
upgrade process.
https://bugzilla.redhat.com/show_bug.cgi?id=2016324
=> controllers: Approve manual installplans

console/console.go
There were a couple of changes introduced in OCP 4.10 which caused the
dynamic plugin to break. 
Signed-off-by: Vineet Badrinath <vineetbnath@gmail.com>
=> console: Fix basepath for odf-console deployment

controllers/quickstart_constants.go
adds one more step "Encrypt your StorageClass" to "Configure and manage OpenShift Data Foundation" QuickStart guide.
Epic URL: https://issues.redhat.com/browse/RHSTOR-1950
Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>
=> controllers: add StorageClass encryption page to ODF QuickStart guide

controllers/subscriptions.go
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2034098
=> controllers: reconcile noobaa subscription before ocs-operator

console/console.go
- ODF 4.10 supports OCP 4.10 and 4.11.
- Updating compatibility build to be activated with OCP 4.11. 
Signed-off-by: Bipul Adhikari <badhikar@redhat.com>
=> console: update compatibility support matrix for 4.10

controllers/quickstart_constants.go
This PR is to revert the changes introduced by https://github.com/red-hat-storage/odf-operator/pull/151
#151 is out of 4.10 now.
Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>
=> controllers: remove StorageClass encryption page from ODF QuickStart guide

controllers/vendors.go
We are using the controller ref to show the vendor CR in the OCP UI and can also use the owner ref for the same.
controller ref is required by the managed services as storageCluster is created by them in the manages services.
changing the controller ref to owner ref will solve the managed services problem.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2044447
Signed-off-by: bindrad <dbindra@redhat.com>
=> controllers: change controller ref to owner ref of the vendor system

.github/workflows/docker-build.yaml
catalog build pulls the bundle images before creating and catalog image
and it does not make sense to download the existing odf-operator-bundle
image from the quay. instead push the current odf-operator-bundle to
local registry and pull it from there.
=> action: Push bundle image to the local registry while testing catalog

bundle/manifests/odf-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/odf-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/odf-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, config/webhook/service.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2043034
Issue
=====
Both csi-addon operator and odf-operator are using the default label and label-selector provided by operator-sdk - "control-plane: controller-manager" for its services and deployments.
This is allowing deployments, services and service monitors of each operator to select the pods ans services of other operator.
One critical impact of this is in UI monitoring where odf metrics monitor is picking up csiaddon service and hence showing an extra storage system. This is breaking the prometheus query and hence missing storage system on UI.
Fix
===
Use a unique label selector in odf-operator to avoid conflicts.
Before:
After:
=> Use a unique label for monitoring resources

controllers/subscriptions.go
This commit adds the following tolerationt to
csi-addons subscription so it is applied to
all the pods it creates.
```
- effect: NoSchedule
key: node.ocs.openshift.io/storage
operator: Equal
value: "true"
```
Currently all the pods related to storage is expected to have the
above toleration to be able to tolerate taints on node dedicated for storage(refer [1]).
The other operators have this in their manager.yaml files. 
By adding this to csiaddons subscription(which will pass it onto any pods created
by it, refer [2}), we can avoid having it in upstream code.
Signed-off-by: Rakshith R <rar@redhat.com>
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2059105
[2] https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#tolerations
=> controllers: add ocs toleration to csi-addons subscription

controllers/storagecluster_controller.go, controllers/storagecluster_controller_test.go
adding an annotation to the storagecluster changes the resource version
of the storagecluster on etcd and ocs-operator fails to update the
status while onboarding the consumer.
There is no easy way to get the id of the storage consumer from the
provider again after the onboarding is successful from the provider end.
minimize the update calls wherever possible.
https://bugzilla.redhat.com/show_bug.cgi?id=2056634
=> controllers: stop adding annotation to the storagecluster

Makefile
running `go mod vendor` while running tests in the container downloads
the all deps again eventhoug they are already installed. Moreover go
already do these checks and verify go.mod with the vendor/modules.txt.
The example runs show this target is not required:
https://github.com/iamniting/odf-operator/runs/4035819892?check_suite_focus=true
https://github.com/iamniting/odf-operator/runs/4035819310?check_suite_focus=true
It does save the unnecessary download twice.
=> makefile: remove vendor-update target

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/manifests/bases/odf-operator.csv.card-description.yaml
Sometimes people think that only with Noobaa they can create `ObjectBucketClaims`.
Probably they forget or don't know about the **ocs-external-storagecluster-ceph-rgw** `StorageClass`.
I added in the Ceph description the "object" volume type.
This is pretty simple, maybe don't do any difference at all but is good to tell about this.
From time to time I got someone thinking in this way.
Thank you!
=> Added a "object storage" description about Ceph

hack/make-tools.mk
Gomega is just a matcher library and it's already in the
go.mod of our project. It need not be installed like the
ginkgo binary. Calling go install on gomega gives a
warning of matched no package.
Signedoff-by: Malay Kumar Parida <mparida@redhat.com>
=> godeps: Remove go install called on gomega

hack/make-tools.mk
while using go get we were always creating a new temp directory and go.mod. So go do not make any changes to the existing go.mod while downloading the binaries. This is not required anymore as go install does not make changes to the existing go.mod if we give the full path with version.
ref: https://go.dev/doc/go-get-install-deprecation
=> makefile: update make-tools and remove unnecessary code

Makefile, e2e/config.go, e2e/setup_teardown.go, pkg/deploymanager/olm.go
We check for all the CSVs, if they have reached succeeded state or not. This is done after the operator installation is completed in the SetUp Function in the BeforeSuite
=> test: Check for all the required CSV names in the SetUp function in the BeforeSuite

pkg/deploymanager/olm.go
Panic was happening in WaitForCatalogsource. So a null check has been
added to that. 
=> Fix panic happening in WaitForCatalogsource

pkg/deploymanager/olm.go
A Panic was happening in WaitForCatalogsource during runtime. So a
null check was added to It. But while doing so a logical mistake was
left behind which allowed it to return true even when the connection
state was nill. Now fixing it.
=> test: Correct logical mistake in fixing panic happening in WaitForCatalogsource

bundle/metadata/dependencies.yaml, controllers/subscriptions.go
csi-addons resolution gets fail when user uses the custom catalog
source as it is not specified in the dependencies.yaml and the sub is
not created via OLM. The sub is created by the odf directly which does
not have a knowledge about the custom catalog source and it is still
pointing to the redhat-operators in the openshift-marketplace namespace.
Managing there own catalog source is seen very offently now a days as it
is MS and disconnected ENV usecase.
https://bugzilla.redhat.com/show_bug.cgi?id=2056697
=> bundle: Add csi-addons to the dependencies.yaml

bundle/metadata/dependencies.yaml, controllers/subscriptions.go
csi-addons resolution gets fail when user uses the custom catalog
source as it is not specified in the dependencies.yaml and the sub is
not created via OLM. The sub is created by the odf directly which does
not have a knowledge about the custom catalog source and it is still
pointing to the redhat-operators in the openshift-marketplace namespace.
Managing there own catalog source is seen very offently now a days as it
is MS and disconnected ENV usecase.
Signed-off-by: Nitin Goyal [nigoyal@redhat.com](mailto:nigoyal@redhat.com)
https://bugzilla.redhat.com/show_bug.cgi?id=2056697
Manual backport of https://github.com/red-hat-storage/odf-operator/pull/221
=> Bug 2093205:[release-4.10] bundle: Add csi-addons to the dependencies.yaml

bundle/manifests/odf-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/odf-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/odf-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, config/webhook/service.yaml
The odf-operator-controller-manager-metrics-service uses only one label
control-plane: controller-manager as pod selector. A different pod also
uses the same label, the service does select the other pod as well along
with our pod and creates issues.
Add the extra label to solve this conflict.
The extra label has been added to all the places except the selector of
odf-operator-controller-manager deployment. As adding the extra label
there causes upgrade failure.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2089342
=> bundle: use extra label for odf-operator configs

controllers/delete.go, controllers/quickstarts.go, controllers/subscription_controller.go, controllers/subscriptions.go
To prevent listing of clusterwide resources unnecessarily, A list
option with the operator namespace as the desired namespace is added
to the places where we are trying to list any resources.
We are trying to fix this BZ [https://bugzilla.redhat.com/show_bug.cgi?id=2092737](https://bugzilla.redhat.com/show_bug.cgi?id=2092737)
Although we haven't been able to find any root cause due to the inability to reproduce the issue, We suspect the listing of unnecessary cluster-wide resources might be one of the causes. So fixing that.
=> controllers: Add namespace as list option while listing resources

controllers/subscriptions.go
This PR prevents subscription config override if it is not empty. This change was made in order to allow users to be able to edit subscription if there is a need for the same (for eg. adding tolerations to underlying objects, etc.)
Following steps were taken to test the changes
1. Steps in the README were followed to deploy ODF with OLM on an OpenShift Cluster.
2. MCG Subscription was edited to add a toleration
3. Manual inspection of subscription confirmed that the config were no longer overridden.
4. Manual inspection of NooBaa operation confirmed that the toleration was propagated to the operator and was persisted.
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
https://bugzilla.redhat.com/show_bug.cgi?id=2122980
=> Prevent subscription config override if it is not empty

main.go, pkg/util/openshift.go
Currently odf-operator is relying on the default "AllNamespaces" cache
in controller-runtime, which works by syncing all the Kubernetes
resources in the cluster. This initial informer cache sync is so huge
that it causes a sudden massive spike in the memory usage of the
operator. It causes OOMKilled failures for the odf-operator pods.
So odf-operator will now set the leaderElectionNamespace & the Manager
cache to the namespace where the operator is deployed. This will
ensure that the initial cache sync will only sync the resources in the
namespace where the operator is deployed.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2092737
=> controllers: limit leaderElection & cache to operator namespace

console/console.go
ODF 4.12 supports OCP 4.12 and 4.13.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
=> console: update compatibility support matrix for 4.12

hack/make-project-vars.mk
Take GOOS and GOARCH make variables from local host (instead of hard-coded linux/amd64), in order to enable build on ARM based machines.
Tested on centos-stream9 aarch64 machine.
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
=> makefile: build on ARM64 machine

main.go, pkg/util/openshift.go
Currently odf-operator is relying on the default "AllNamespaces" cache in controller-runtime, which works by syncing all the Kubernetes resources in the cluster. This initial informer cache sync is so huge that it causes a sudden massive spike in the memory usage of the operator. It causes OOMKilled failures for the odf-operator pods.
So odf-operator will now set the leaderElectionNamespace & the Manager cache to the namespace where the operator is deployed. This will ensure that the initial cache sync will only sync the resources in the namespace where the operator is deployed.
=> Bug 2129852:controllers: limit leaderElection & cache to operator namespace

main.go, pkg/util/openshift.go
Currently odf-operator is relying on the default "AllNamespaces" cache in controller-runtime, which works by syncing all the Kubernetes resources in the cluster. This initial informer cache sync is so huge that it causes a sudden massive spike in the memory usage of the operator. It causes OOMKilled failures for the odf-operator pods.
So odf-operator will now set the leaderElectionNamespace & the Manager cache to the namespace where the operator is deployed. This will ensure that the initial cache sync will only sync the resources in the namespace where the operator is deployed.
=> Bug 2129853:controllers: limit leaderElection & cache to operator namespace

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
Having v=10 dumps sensitive information like tokens, resulting in information leakage if these logs are obtained. The Kubebuilder team also made this fix. They are also using v=0 now.
Ref: https://github.com/kubernetes-sigs/kubebuilder/pull/2435
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2136852
=> bundle: remove debug logging from the manager auth proxy patch

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/console/console_init.yaml
BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=2166417
Issue: 115558: Misconfigured Security Context Attribute For A Pod Or Container
set securityContext for odf-console pod/container as per best practices.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
=> console: configure securityContext for odf-console

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/console/console_init.yaml
This reverts commit 363419365ccd6c8fafe200e80b9d0bc0d9a232af.
SecurityContext: "readOnlyRootFilesystem: true" is causing odf-console pod crashloopbackoff. Nginx used downstream is trying to create some temp files but don't have access to do so, hence pod is never getting into "Running" status.
Will create a new PR without setting "readOnlyRootFilesystem" context for the container. And need to check why nginx wants such access.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
=> Revert "console: configure securityContext for odf-console"

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
Having v=10 dumps sensitive information like tokens, resulting in information leakage if these logs are obtained. The Kubebuilder team also made this fix. They are also using v=0 now.
Ref: https://github.com/kubernetes-sigs/kubebuilder/pull/2435
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2136852
Backport of https://github.com/red-hat-storage/odf-operator/pull/271
=> Bug 2168035:[release-4.11] bundle: remove debug logging from the manager auth proxy patch

console/console.go
ODF 4.13 supports OCP 4.13 and 4.14.
Signed-off-by: Timothy Asir <tjeyasin@redhat.com>
=> console: update compatibility support matrix for 4.13

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
Having v=10 dumps sensitive information like tokens, resulting in information leakage if these logs are obtained. The Kubebuilder team also made this fix. They are also using v=0 now.
Ref: https://github.com/kubernetes-sigs/kubebuilder/pull/2435
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2136852
Backport of https://github.com/red-hat-storage/odf-operator/pull/271
=> Bug 2168036:[release-4.10] bundle: remove debug logging from the manager auth proxy patch

controllers/defaults.go, controllers/subscriptions.go
Avoid using the cached sub of odf in a way that assumes it will always exist, because if someone deletes it, the odf operator will still have the same cache and will create new subs using the UID of the deleted odf sub. These new subs will then be marked for garbage collection by Kubernetes since the old odf sub UID no longer exists.
https://bugzilla.redhat.com/show_bug.cgi?id=2178619
=> controllers: do not use odf sub cache

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/console/console_init.yaml, console/console.go, console/nginx_conf.go, controllers/clusterversion_controller.go
Changes required as per BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2139785
1.  BZ#2139785 itself: where on **disabling ipv6 address on the cluster nodes**, odf-console pod was resulting in error state (https://bugzilla.redhat.com/show_bug.cgi?id=2139785#c10)
2. There was CVE issue raised by IBM team where port 8080 was stated to be an insure port (https://bugzilla.redhat.com/show_bug.cgi?id=2166417). Port 8080 is present by default in the nginx configuration that we use for our pod (under `/etc/nginx/nginx.conf`: https://pastebin.com/ksX21dsr) and we did not had any control over that config earlier. Now all the nginx configurations (nginx's default and custom config for odf-console) are added via a ConfigMap created by odf-operator, so everything is under our control.
Also, now …
=> add nginx configurations for the odf-console

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/console/console_init.yaml, console/nginx_conf.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2166417
NGINX requires some dirs to be writable so we enable 2 `emptyDir` volumes for that purpose and update the NGINX config with the path of those dirs.
NOTE: when using the downstream image, we noticed this in the pod logs:
```/opt/app-root/etc/generate_container_user: line 6: /opt/app-root/etc/passwd: Read-only file system```
After a conversation with @SanjalKatiyar and Boris Ranto we decided to not take any action on this as it has no side effects on the behavior of the container.
=> console: securityContext: add 'readOnlyRootFilesystem'

Makefile, bundle/manifests/odf-operator.clusterserviceversion.yaml, config/manifests/bases/kustomization.yaml, hack/make-bundle-vars.mk
The annotation will allow OCP upgrade till given max OCP version which
is X+1. For example the ODF version is 4.13 the max OCP version would
be 4.14.
Ref: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/operators/index#:~:text=If%20you%20know,the%20cluster%20version
=> makefile: block OCP upgrades beyond the X+1 version

console/console.go, controllers/clusterversion_controller.go
The mutateFunciton is updated to modify the configmap
Currently, when ODF is upgraded the ConfigMap data does not get updated. Hence the container crashes. This updates the configmap which should stop the crash. 
The configmap holds configuration related to Nginx. 
In ODF 4.13 the pid directive was pointing to `/run/nginx.pid` which was updated to `/var/lib/nginx/tmp/nginx.pid`.
Based on above change we set `readOnlyRootFilesystem` to `true`. 
As the ConfigMap was not updated Nginx tried creating a file at `/run/nginx.pid`.
=> console: Fixes reconciliation logic for console ConfigMap

console/console.go
ODF 4.14 supports OCP 4.14 and 4.15.
=> console: update compatibility support matrix for 4.14

main.go
Multiple storagecluster requires client to watch multiple namespaces
=> Watch for specific set of namespaces using the client

controllers/subscriptions.go
If ROLEARN env variable is set, then pass on that env variable to noobaa subscription.
Ref: https://issues.redhat.com/browse/RHSTOR-5139
=> set ROLEARN env variable in noobaa subscription

console/console.go
ODF 4.15 supports OCP 4.15 and 4.16.
=> console: update compatibility support matrix for 4.15

console/console.go
Adds proxy for console to connect to the token generation server. This is required for Provider mode on-boarding feature.
=> Adds proxy for Provider mode backend in ConsolePlugin

controllers/clusterversion_controller.go
ConsolePlugin gets correctly updated in upgrade scenarios
Fixes [Bug 2258015](https://bugzilla.redhat.com/show_bug.cgi?id=2258015)
=> console: Fixes update issue in ConsolePlugin

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/samples/ibm-flashsystemcluster-storagesystem.yaml, config/samples/ocs-storagecluster-storagesystem.yaml
In certain instances customers unintentionally create two storagesystems to the same storagecluster. This becomes problematic when attempting to delete one storagesystem, as it triggers the deletion of the associated storagecluster. By changing the name and reference, we aim to prevent this issue from occurring.
It will make sure that even if they create the storagesystem from the OCP console it wont refer to the same storagecluster.
Bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=2263441
https://bugzilla.redhat.com/show_bug.cgi?id=2254343
=> bundle: Modify the name and reference of the sample storagesystem

controllers/subscriptions.go, controllers/subscriptions_test.go
=> controllers: replicate odf tolerations to child subscriptions

console/console.go
ODF 4.16 supports OCP 4.16 and 4.17.
=> console: update compatibility support matrix for 4.16

controllers/storagesystem_controller.go, controllers/subscription_controller.go, controllers/subscriptions.go
Client operator manages its own upgrade life cycle in the provider mode, Do not update its channel in the provider mode.
=> controllers: Do not update client operator in provider mode

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
This is an manual cherry-pick of https://github.com/red-hat-storage/odf-operator/pull/396
=> Bug 2274098:[release-4.15] bundle: add readOnlyRootFilesystem for odf-operator

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/samples/ibm-flashsystemcluster-storagesystem.yaml, config/samples/ocs-storagecluster-storagesystem.yaml
This is an manual cherry-pick of #370
=> Bug 2263475:[release-4.12] bundle: Modify the name and reference of the sample storagesystem

controllers/subscriptions.go, controllers/subscriptions_test.go
skipping rook subscription reconcile lead to the tolerations being absent from the rook subscription.
This fix is only required in 4.16 due to the #399
=> Bug 2276913:[release-4.16] controllers: do not skip rook subscription reconcile

bundle/metadata/dependencies.yaml, controllers/subscriptions.go
This reverts commit 8907814c021e38ef776ce95dff51d18d5fecf85b.
4.17 onwards odf will take a ownership over rook and bring it as a OLM deps.
Related PR: #399, #402
=> Revert "bundle: remove rook as a dependency to allow upgrades from 4.15 to 4.16"

controllers/subscriptions.go
CSI addons will be managed by the ocs-client-operator in the provider mode.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2280818
Related PR: #393
=> controllers: Do not manage csi addons if running in provider mode

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/rbac/role.yaml, console/console.go, controllers/clusterversion_controller.go
https://issues.redhat.com/browse/RHSTOR-5204
No straight-forward/correct way of CLI Tool CR deletion (clean-up) is currently possible (**during operator uninstallation**).
1. Tried deleting from `clusterversion_controller`, as part of reconcile (https://github.com/red-hat-storage/odf-operator/pull/410#discussion_r1607017878).
2. Tried adding CR as part of the ODF bundle for OLM to maintain (https://github.com/operator-framework/operator-registry/blob/master/pkg/lib/bundle/supported_resources.go#L21 & https://github.com/red-hat-storage/odf-operator/pull/417#discussion_r1608233489).
3. One other way could be to add a finaliser to the manager pod which will be removed by `clusterversion_controller` once clean-up is done, but dropped this approach entirely after discussion due to hack-ish …
=> Add the option to download the ODF CLI tool from the UI

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
This is a manual cherry-pick of #396
=> Bug 2274099: [release-4.14] bundle: add readOnlyRootFilesystem for odf-operator

controllers/storagesystem_controller.go, controllers/subscriptions.go
The ocs-client-operator is a dependency of the odf-operator, which gets installed regardless of whether the cluster is in provider mode. However, the client operator is not needed in non-provider mode. This change ensures that the client operator is shut down if the cluster is not in provider mode.
https://issues.redhat.com/browse/DFBUGS-17
https://bugzilla.redhat.com/show_bug.cgi?id=2299443
=> controllers: Shut down OCS client CSV pods if not in provider mode

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/samples/ibm-flashsystemcluster-storagesystem.yaml, config/samples/ocs-storagecluster-storagesystem.yaml
This is an manual cherry-pick of #370
=> Bug 2263474:[release-4.13] bundle: Modify the name and reference of the sample storagesystem

bundle/manifests/odf-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/storagesystem_controller.go, controllers/subscriptions.go
Delete the webhook created by the ocs-client-operator as the client operator is already down in the 4.16.1 and it can not delete the webhook itself. Deleting the webhook will allow us the upgrades from 4.16 to 4.17. Otherwise it will always hit an error "failed calling webhook" while updating the channel of the ocs-client-operator subscription.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2304073
=> controllers: delete the webhook created by the ocs-client-operator

hack/aws-cleanup.sh
=> hack: cleanup noobaa stale buckets in the aws

go.mod, go.sum, vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go, vendor/modules.txt
Update ocs-operator pkg version to include new api changes
Ref BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2276694
=> Bug 2296521: [release-4.16] api: update ocs-operator pkg version

console/console.go
ODF 4.18 supports OCP 4.18 and 4.19.
=> console: update compatibility support matrix for 4.18

go.mod, go.sum, vendor/modules.txt
github.com/census-instrumentation/opencensus-go repository was archived on the Jul 31, 2023 and url go.opencensus.io holding these libraries is not available anymore. Though it is still available on the proxy server.
But we are using GOPROXY="direct,https://proxy.golang.org" which tries to fetch it from the go.opencensus.io and throws an error. To fix this we are now starting pulling it directly from the github archived repo.
once we start using GOPROXY="https://proxy.golang.org,direct" we can revert this change as well.
while reverting 6cb13e914938e7c8d2832fde0b930cebcb84a98e we also need to revert this. Related PR (#479)
Ref: 
https://github.com/googleapis/google-cloud-go/issues/11481 
https://github.com/kubernetes-sigs/kubetest2/pull/287
=> godeps: fix an error 'unrecognized import path "go.opencensus.io"'

Dockerfile, catalog.deps.Dockerfile
Docker requires consistent casing for keywords.
If a keyword is in uppercase, all keywords should be in uppercase. 
If a keyword is in lowercase, all keywords should be in lowercase.
The following warning appears while building images:
FromAsCasing: 'as' and 'FROM' keywords' casing do not match
=> dockerfile: fix casing warning in Dockerfile

Dockerfile, catalog.deps.Dockerfile, go.mod, go.sum, vendor/modules.txt
PR containing the latest commits from main branch
=> Syncing latest changes from main for odf-operator

controllers/clusterversion_controller.go
Remove the conditional check to ensure the console plugin proxy is always updated. This change addresses upgrade scenarios where the previous version had only two proxies, and a third (noobaa s3) one has now been added.
Bug: https://issues.redhat.com/browse/DFBUGS-1830
=> console: Always update console plugin proxy

bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/operatorscaler_controller.go, go.mod, main.go
=> create a operator scaler controller to add dynamic watches on CRs and scale operators

Dockerfile, bundle/odf-operator/manifests/odf-operator-webhook-server-service_v1_service.yaml, bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml, config/default/kustomization.yaml, config/default/manager_webhook_patch.yaml, config/manager/kustomization.yaml, config/manager/webhook_service.yaml, config/rbac/role.yaml, controllers/storagesystem_controller.go, controllers/subscription_controller.go, controllers/webhook.go, main.go, webhook/csv.go
=> Create a CSV webhook

bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml, config/manifests/bases/odf-operator.clusterserviceversion.yaml, controllers/webhook.go
Relying on the OLM label was unreliable as it gets added after CSV creation, causing the webhook to trigger for odf-operator CSV.
This change adds a custom label to ensure the webhook skips the odf-operator CSV during creation.
It prevents issues where uninstalling and reinstalling ODF blocks odf-operator CSV creation due to webhook CR presence in the cluster, while the odf-operator is absent to serve the webhook requests.
=> controllers: add custom label to odf CSV to skip webhook call

console/console.go
ODF 4.19 supports OCP 4.19 and 4.20.
=> console: update compatibility support matrix for 4.19

Makefile, bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml, bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml, config/manager/mapping.yaml, config/rbac/role.yaml, controllers/operatorscaler_controller.go, controllers/subscription_controller.go, controllers/subscriptions.go
This PR ensures that we:
1. Always run client op from 4.19
2. Don't update the sub-channel for client-op, csi-add & csi-op
Ref: [RHSTOR-7170](https://issues.redhat.com/browse/RHSTOR-7170)
=> controllers: remove provider mode reference from odf

controllers/config.go
If the struct is not reset before unmarshaling, old values persist when new YAML data omits certain keys. This can lead to incorrect configurations being processed.
Now, record is explicitly reset to its zero state before each unmarshal operation, ensuring no leftover values from previous iterations affect the result.
=> controllers: Reset struct before unmarshaling to prevent stale values

controllers/defaults.go, controllers/subscriptions.go
Previously, we only updated the catalog source for the odf-dependencies subscription. This change extends the logic to update the catalog source for odf-dependencies as well as cnsa-dependencies subscription.
=> controllers: update catalog source for all dependencies subscriptions
