- .github/workflows/codespell.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/golangci-lint.yaml
- controllers/storagesystem_controller.go
As part of the pr below tasks are done:
* Add StorageSystem initial controller
* Add github actions
Signed-off-by: Nitin Goyal nigoyal@redhat.com
> Add github actions and initial controller

- Makefile
> makefile: change controller image name

- controllers/conditions_test.go
- controllers/storagesystem_controller_fake.go
- controllers/subscriptions_test.go
- go.mod
> Add controller unit tests

- webhook/subscription/mutatingwebhook_test.go
- webhook/subscription/validatingwebhook_test.go
This should be merged after https://github.com/red-hat-data-services/odf-operator/pull/7
> test: Add subscription webhook unit tests

- api/v1alpha1/storagesystem_types.go
* Add kubebuilder tags which will validate CR upon create/update operation
* Append the apiVersion in the names of StorageKind variable
> api: Change StorageSystem spec

- .github/workflows/conf/commitlintrc.json
- CONTRIBUTING.md
> action: Add missing types in commitlint action

- .github/workflows/conf/commitlintrc.json
> action: fix typo in commitlint action config

- webhook/subscription/validatingwebhook.go
> webhook: correct name of validatingwebhook

- api/v1alpha1/storagesystem_types.go
Change StorageSystemSpec.NameSpace json feild from nameSpace to
namespace.
> api: change nameSpace to namespace in the spec

- Makefile
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- bundle/manifests/odf.openshift.io_storagesystems.yaml
- config/crd/bases/odf.openshift.io_storagesystems.yaml
- config/manager/kustomization.yaml
- config/rbac/role.yaml
- config/samples/odf_v1alpha1_storagesystem.yaml
- config/webhook/manifests.yaml
This PR includes some small fixes here and there:
- update catalog image variables
- update the sample CR
- update manifests
- update bundle
> update makefile and manifests

- .github/workflows/docker-build.yaml
- Dockerfile
- Makefile
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
- hack/get-tool.sh
- hack/go-build.sh
- hack/make-bundle-vars.mk
- hack/make-help.sh
- hack/make-project-vars.mk
- hack/make-tools.mk
Primarily looking to provide clean parameterization for integration with various CI systems.
> makefile: Overhaul makefile automation

- Dockerfile
- Makefile
- hack/go-build.sh
Fix a problem with CGO in the go build and optimize the docker build.
> makefile: go build improvements

- .github/workflows/docker-build.yaml
> action: build catalog image as well in the action

- .github/workflows/conf/commitlintrc.json
- CONTRIBUTING.md
> action: Add hack as a type in commitlintrc

- hack/make-bundle-vars.mk
> hack: split dependent bundle images into two name and tag

- OWNERS
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
> ci: add OWNERS file

- Makefile
- config/install/ibm-storage-odf-operator-subscription.yaml
- config/install/kustomization.yaml
- config/install/odf-catalogsource-image.yaml
- config/install/odf-catalogsource.yaml
- config/install/odf-operator-subscription.yaml
- config/install/openshift-storage-namespace.yaml
- config/install/openshift-storage-operatorgroup.yaml
- config/install/storagesystem-flashsystemcluster.yaml
Use kustomize to create and delete operator via OLM.
> Makefile: Create a target to install and uninstall operator via OLM

- api/v1alpha1/storagesystem_types.go
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/storagesystem_controller.go
- controllers/subscriptions.go
> update phase in the status of storagesystem

- Dockerfile
- Makefile
- bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manager/manager.env
- config/manager/manager.yaml
- hack/make-bundle-vars.mk
> Add a method to feed env variables to the configmap of manager

- Dockerfile
- controllers/storagesystem_controller.go
- go.mod
- metrics/metrics.go
- metrics/metrics_test.go
Add metrics for StorageSystem spec so that we can use Prometheus queries to understand object relationships.
> Add metrics for StorageSystem spec

- Dockerfile
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/console/console_init.yaml
- config/console/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manifests/kustomization.yaml
- console/console.go
- go.mod
- go.sum
- main.go
- Creates a Deployment which contains the Web Server
- Creates a Service to expose the above Deployment
- Creates a ConsolePlugin to expose ODF Console Plugin to the OCP Core console. 
cc @jarrpa @umangachapagain @iamniting
> Add initialization code for ODF Console

- .github/workflows/conf/commitlintrc.json
- CONTRIBUTING.md
> action: Add console,metrics as a type in the commitlintrc

- api/v1alpha1/storagesystem_types.go
- controllers/storagesystem_controller.go
> set phase error if spec validation fails

- Makefile
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- hack/make-bundle-vars.mk
> set kube-rbac-proxy image via kustomize with make target

- controllers/events.go
- controllers/events_test.go
- controllers/storagecluster_controller.go
- controllers/storagecluster_controller_fake.go
- controllers/storagesystem_controller.go
- controllers/storagesystem_controller_fake.go
- main.go
> controllers: Generate events for the storagesystem and storagecluster

- bundle/metadata/dependencies.yaml
> bundle: update ocs dependencies version

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
> Add required information in the CSV to show in the UI

- controllers/quickstart_constants.go
Updated quickstart guide for `odf-configuration` & `getting-started-odf`.
> Update ODF QuickStart

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/samples/ibm-flashsystemcluster-storagesystem.yaml
- config/samples/kustomization.yaml
- config/samples/ocs-storagecluster-storagesystem.yaml
- config/samples/odf_v1alpha1_storagesystem.yaml
> update samples of storagesystem

- bundle/manifests/odf-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- bundle/manifests/odf-operator-controller-manager-metrics-service_rbac.authorization.k8s.io_v1_role.yaml
- bundle/manifests/odf-operator-controller-manager-metrics-service_rbac.authorization.k8s.io_v1_rolebinding.yaml
- config/default/kustomization.yaml
- config/rbac/kustomization.yaml
- config/rbac/metrics_service_role.yaml
- config/rbac/metrics_service_role_binding.yaml
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>
Tested in the openshift-storage namespace.
> config: Add resources to enable Prometheus Monitoring

- console/console.go
Fix PodSelector to route traffic to server pod
Signed-off-by: bipuladh <badhikar@redhat.com>
> console: Fix PodSelector label

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
> bundle: Add vendor kind annotation to the csv

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/install/odf-operator-subscription.yaml
- hack/make-bundle-vars.mk
> bundle: Update csv version to 4.9.0

- bundle/metadata/dependencies.yaml
- hack/make-bundle-vars.mk
> Add noobaa as a dependency 

- bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/console/kustomization.yaml
- config/manager/manager.env
- hack/make-bundle-vars.mk
> Update IBM console and CSV version to 0.2.1

- CONTRIBUTING.md
> docs: Update contribution guide

- CONTRIBUTING.md
> docs: Add guidelines for updating CSV in CONTRIBUTING guide

- .github/workflows/commitlint.yaml
- .github/workflows/conf/commitlintrc.json
reference:
https://github.com/wagoid/commitlint-github-action/issues/187
> action: Fix the commitlint action for signed-off

- bundle.Dockerfile
- bundle/manifests/odf-operator-controller-manager_v1_serviceaccount.yaml
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- hack/make-tools.mk
Fix: "Error: Value odf-operator-controller-manager: invalid service
account found in bundle. sa name cannot match service account defined
for deployment spec in CSV".
References:
https://github.com/operator-framework/operator-sdk/issues/5244
https://github.com/operator-framework/operator-sdk/issues/5326
https://bugzilla.redhat.com/show_bug.cgi?id=2021119
> bundle: fix validation error via removing SA manifest

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/console/console_init.yaml
- config/manager/manager.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=2022776
> bundle: Add tolerations on manager and console pod

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.csv.card-description.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1994606
> bundle: update card description for UI

- .github/workflows/docker-build.yaml
> action: update golang version from 1.15 to 1.17

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2035995
> bundle: increase memory of the controller

- controllers/subscriptions.go
while upgrading odf-operator odf-operator csv get deleted and replaced
with the new one. which cause ocs-operator, mcg-operator to be deleted
as the odf-operator csv was the owner to the ocs-operator, mcg-operator.
To prevent ocs-operator, mcg-operator to be deleted we need to remove
odf-operator CSV as a owner and add odf-operator subscription as a owner
for the garbage collector.
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2034805
> controllers: remove odf CSV as a owner to other CSV's and add odf sub

- controllers/quickstart_constants.go
Minor fixes to gettingStarted and odfConfigAndManagement QS guides.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2004916
Signed-off-by: sanjalkatiyar <sanjaldhir@gmail.com>
> controllers: minor QuickStart guide fixes

- bundle/manifests/odf-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- bundle/manifests/odf-operator-controller-manager-metrics-service_v1_service.yaml
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_service.yaml
- config/webhook/service.yaml
This reverts commit 996fb171f6c710c28be15bc7651ae550026fd836.
Signed-off-by: Afreen Rahman <afrahman@redhat.com>
> Revert "bundle: Use a unique label for monitoring resources"

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.csv.card-description.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=2024424
> bundle: update operator card description

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=2058185
> bundle: Add infrastructure-features annotation to the csv

- .github/workflows/docker-push.yaml
The action will push images only if someone triggers it and ask inputs
from a user.
> action: Add manual github action to push images to quay

- bundle/metadata/dependencies.yaml
> bundle: update ocs-operator version in the bundle dependencies

- .github/workflows/commitlint.yaml
- PROJECT
- README.md
- controllers/clusterversion_controller.go
- controllers/conditions.go
- controllers/delete.go
- controllers/delete_test.go
- controllers/quickstarts_test.go
- controllers/storagecluster_controller.go
- controllers/storagecluster_controller_test.go
- controllers/storagesystem_controller.go
- controllers/storagesystem_controller_fake.go
- controllers/subscription_controller.go
- controllers/subscriptions.go
- controllers/subscriptions_test.go
- controllers/vendors.go
- controllers/vendors_test.go
- go.mod
- main.go
> Rename red-hat-data-services to red-hat-storage

- pkg/deploymanager/olm.go
Previously this was using client.List which was causing a problem
because of empty csvlist condition. Now it will use client.Get on
specific csv name that is passed at the time of making the e2e test.
> test: Fix WaitForCsv fucntion in the deploymanager package

- console/console.go
- controllers/clusterversion_controller.go
BasePath needs to be set as per the version of the OCP cluster
Signed-off-by: Bipul Adhikari <badhikar@redhat.com>
> Bug 2064314: console: update basePath for ConsolePlugin

- controllers/storagesystem_controller.go
Client update call does not update the status and replace the in memory
status with the empty status from the etcd server, which causes status
loss. Save the status locally so it can be replaced after a update call.
Also refactor the finalizers logic a bit
https://bugzilla.redhat.com/show_bug.cgi?id=2086423
> controllers: refactor the update call and finalizers logic

- .github/workflows/conf/commitlintrc.json
- .github/workflows/golangci-lint.yaml
- Dockerfile
- Makefile
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/kustomization.yaml
- controllers/suite_test.go
- hack/e2e-test.sh
- hack/go-test-setup.sh
- hack/go-test.sh
- hack/make-bundle-vars.mk
- hack/make-project-vars.mk
- hack/make-tools.mk
- index.Dockerfile
These are a bulk of patches I've been maintaining in my working branch for a while. I've been using them regularly, so at least they WFM and I think I've done an all right job of keeping them out of the way for anyone who doesn't want them.
> Several pent up frustrations ;)

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2114066
> bundle: update quotes in the valid-subscription annotation

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/console/console_init.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/manager/manager.yaml
> update securityContext in all containers

- .github/workflows/codespell.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/docker-push.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mirror-noobaa-upstream-images.yaml
- .github/workflows/yamllint.yaml
- Makefile
- hack/make-project-vars.mk
> makefile: fix lint Makefile target and update all actions versions

- .github/workflows/codespell.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/docker-push.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mirror-noobaa-upstream-images.yaml
- .github/workflows/yamllint.yaml
> update github actions

- .github/workflows/codespell.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/conf/commitlintrc.json
- .github/workflows/dependencies.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/docker-push.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mirror-noobaa-upstream-images.yaml
- .github/workflows/yamllint.yaml
- controllers/suite_test.go
actions are failing for long time, pull all action updates from main
> action: update github actions for release-4.10

- .github/workflows/commitlint.yaml
- .github/workflows/conf/commitlintrc.json
- .github/workflows/conf/yamllint.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/docker-push.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mirror-noobaa-upstream-images.yaml
- .github/workflows/yamllint.yaml
- config/certmanager/kustomizeconfig.yaml
- controllers/suite_test.go
actions are failing for long time, pull all action updates from main
> action: update github actions for release-4.9

- .github/workflows/codespell.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/conf/commitlintrc.json
- .github/workflows/dependencies.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/docker-push.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/mirror-noobaa-upstream-images.yaml
- .github/workflows/yamllint.yaml
- controllers/suite_test.go
actions are failing for long time, pull all action updates from main
> action: update github actions for release-4.11

- controllers/suite_test.go
> controllers: fix go fmt issue

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- bundle/metadata/dependencies.yaml
- config/default/kustomization.yaml
- index.Dockerfile
- pkg/deploymanager/namespace.go
> make required changes for the bundle and e2e tests

- .github/workflows/docker-build.yaml
> action: check for uncommitted bundle changes

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/console/console_init.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/manager/manager.yaml
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>
> Add/update securityContext for containers

- .github/workflows/docker-build.yaml
- bundle.Dockerfile
- bundle/manifests/odf-operator.clusterserviceversion.yaml
- bundle/manifests/odf.openshift.io_storagesystems.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/odf.openshift.io_storagesystems.yaml
- config/manager/manager.yaml
- config/rbac/role.yaml
- controllers/suite_test.go
- hack/make-bundle-vars.mk
- hack/make-tools.mk
> makefile: update operator-sdk version

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2222863
> Bug 2222863:[release-4.10] bundle: add the valid-subscription annotation

- .github/workflows/docker-build.yaml
- .github/workflows/docker-push.yaml
- .github/workflows/golangci-lint.yaml
- Dockerfile
- go.mod
> godeps: update go version

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/clusterversion_controller.go
- controllers/storagesystem_controller.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2114839
> controllers: remove * and update correct permission

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
Added an annotation to odf-operator CSV for STS support.
Ref: https://issues.redhat.com/browse/RHSTOR-5097
> add annotation for STS support

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/samples/ibm-flashsystemcluster-storagesystem.yaml
- config/samples/ocs-storagecluster-storagesystem.yaml
PR containing the latest commits from main branch
> Syncing latest changes from main for odf-operator

- controllers/subscriptions.go
- hack/make-bundle-vars.mk
> controllers: add Prometheus csv in the csv list

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2273386
> bundle: add readOnlyRootFilesystem for odf-operator

- .github/workflows/aws-cleanup.yaml
> action: update the aws cleanup action

- .github/workflows/aws-cleanup.yaml
- hack/aws-cleanup.sh
> action: update aws cleanup action

- hack/aws-cleanup.sh
> hack: update the aws cleanup script to delete few other resources

- hack/install-odf.sh
> hack: update script to print debug output of csv and pods

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/samples/ibm-flashsystemcluster-storagesystem.yaml
- config/samples/ocs-storagecluster-storagesystem.yaml
This is an manual cherry-pick of #370
> Bug 2263473:[release-4.14] bundle: Modify the name and reference of the sample storagesystem

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/console/console_init.yaml
Bug link: https://bugzilla.redhat.com/show_bug.cgi?id=2302857
> bundle: Stop service account token from being automatically mounted in odf-console

- hack/make-tools.mk
pin ginkgo version to same as go.mod file in tool script
> [release-4.13] makefile: pin gingko version in tools script

- hack/make-tools.mk
pin ginkgo version to same as go.mod file in tool script
> pin gingko version in tools script

- hack/make-tools.mk
pin ginkgo version to same as go.mod file in tool script
> [release-4.16] makefile: pin gingko version in tools script

- hack/make-tools.mk
pin ginkgo version to same as go.mod file in tool script
> [release-4.15] makefile: pin gingko version in tools script

- .github/workflows/docker-build.yaml
- Makefile
> makefile: add target to checkout timestamp only changes in bundle

- .github/workflows/docker-build.yaml
The code was removed as part of the #502 But comment was left.
> action: remove comment

- .github/workflows/docker-build.yaml
- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- vendor/modules.txt
> Add few tweaks

- console/console.go
Fixes: https://issues.redhat.com/browse/RHSTOR-6844
Blocks: https://github.com/red-hat-storage/odf-console/pull/1833
> console: add proxy declaration for S3 service

- catalog.deps.Dockerfile
Replace the image reference in odf-dependencies.yaml
> dockerfile: update catalog.deps.Dockerfile

- catalog.deps.Dockerfile
This reverts commit a0aaa6c71d60345194d0adfcf1402ff594ec83cc.
I created this commit to test the build args in the openshift-ci.
> Revert "dockerfile: update catalog.deps.Dockerfile"

- Makefile
- hack/install-odf.sh
- hack/make-bundle-vars.mk
> makefile: update odf-deps catalog variables

- hack/install-odf.sh
> ci: always print the logs in case of failure or success in the CI

- controllers/operatorscaler_controller.go
> controllers: remove the reconcile related variables from the reconciler

- Makefile
- bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml
- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manager/mapping.yaml
> Makefile: Add new keys to the configmap

- controllers/operatorscaler_controller.go
- controllers/storagesystem_controller.go
Related PR: https://github.com/red-hat-storage/ocs-operator/pull/3090
> Move the creation of metrics to operatorScaler controllers

- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/cleanup_controller.go
- main.go
ownerref of the storagesystem was being added to the storagecluster and flashsystemcluster, As storagesystem is being removed we need to delete the storagesystem ownerref from these CRs and delete the storagesystem.
> controllers: remove the storagesystem ownerref and delete storagesystem

- controllers/cleanup_controller.go
keeping the log as variable name replaces the log pkg
> controllers: rename log variable to logger

- controllers/subscription_controller.go
- main.go
> controllers: convert subscription `For` controller to named controller

- controllers/common_test.go
- controllers/quickstarts_test.go
- hack/install-odf.sh
> some small fixes in tests and ci

- controllers/subscription_controller.go
- controllers/subscriptions.go
> Subs refactor

- go.mod
- go.sum
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/write.go
- vendor/golang.org/x/net/internal/httpcommon/ascii.go
- vendor/golang.org/x/net/internal/httpcommon/headermap.go
- vendor/golang.org/x/net/internal/httpcommon/request.go
- vendor/modules.txt
Bug: https://issues.redhat.com/browse/DFBUGS-1988
> godeps: fix CVE-2025-22870

- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/config.go
- controllers/subscription_controller.go
- controllers/subscriptions.go
> Switch to dynamic mapping for the subscription controller

- webhook/csv.go
> controllers: use configmap to get the csv names for webhook

- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- controllers/operatorscaler_controller.go
- metrics/metrics.go
- metrics/metrics_test.go
This PR fixes the issue where metrics are not being exported, which was broken by #514.
> Fix metrics and metrics exporter

- controllers/operatorscaler_controller.go
> controllers: use dynamic mapping for operatorscaler controller

- controllers/operatorscaler_controller.go
> controllers: fix parse logic in the loadOdfConfigMapData

- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/cleanup_controller.go
- controllers/operatorscaler_controller.go
Bug: https://issues.redhat.com/browse/DFBUGS-2069 (Comment 1 From Vijay)
> Fix panic and permission issue for setting owner ref

- webhook/csv.go
> controllers: fix pointer panic in webhook

- bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
Fixes https://issues.redhat.com/browse/DFBUGS-2118
> Update CSV to support initialization link feature of OLM

- bundle/manifests/odf-operator.clusterserviceversion.yaml
- config/manifests/bases/odf-operator.clusterserviceversion.yaml
Manual Backport of https://github.com/red-hat-storage/odf-operator/pull/621
> DFBUGS-3694:[release-4.14] bundle: add uninstall warning for console
